import React, {useState,useEffect,useRef} from 'react';
import {Choices,NumberField} from './PieceSetup';
import TabView from './TabView';
import VolumeControls from './VolumeControls';
import {prepareGuitar,pluck,stopGuitar} from './guitarSynth';
import {primeMetronomeAudio,getAudioContext} from '../shared/metronome';
import {fmtClock} from './storage';
import {PAUSE_OPTIONS} from './timing';
const combos=['12','13','14','23','24','34','123','124','134','234','1234'];
export function PatternRating({records,position,bpm}) {
 const [saved,setSaved]=useState(()=>{try{return JSON.parse(localStorage.getItem('workouts.patternRatings.v1')||'{}');}catch{return {};}});
 const [notice,setNotice]=useState('');
 function mark(rating) {
  const next={...saved};for(const r of records){const key=`${position}:${r.id}:${r.stroke}`;if(rating)next[key]={rating,bpm,position,updatedAt:new Date().toISOString()};else delete next[key];}
  try{localStorage.setItem('workouts.patternRatings.v1',JSON.stringify(next));setSaved(next);setNotice(rating?'Assessment saved at '+bpm+' BPM.':'Assessment cleared.');}catch{setNotice('Could not save on this device.');}
 }
 return <details className="cp-timing"><summary>Confidence · {records.length} pattern{records.length===1?'':'s'}</summary><p>Your assessment at position {position}, {bpm} BPM.</p><div className="cp-choices">{[['red','! Needs work'],['yellow','~ Getting there'],['green','✓ Comfortable'],[null,'Clear']].map(([r,t])=><button key={t} style={r?{borderColor:({red:"#e87979",yellow:"#dfbe64",green:"#7ccc9c"})[r]}:{}} onClick={()=>mark(r)}>{t}</button>)}</div>{records.length===1 && records.map(r=>{const v=saved[`${position}:${r.id}:${r.stroke}`];return v?<p key={r.id+r.stroke}>{r.id.replaceAll('-',' · ')} · {r.stroke==='D'?'Downstroke':'Upstroke'} · {({red:'! Needs work',yellow:'~ Getting there',green:'✓ Comfortable'})[v.rating]} at {v.bpm} BPM</p>:null;})}<p role="status">{notice}</p></details>;
}
export default function PickingSetup(p){
 const {workout,exercises,practiceMode,setPracticeMode,focusCombo,setFocusCombo,focusCrossing,setFocusCrossing,bothStrokes,setBothStrokes,position,setPosition,startStroke,setStroke,groups,setGroups,bpm,setBpm,loopMode,setLoopMode,loopReps,setLoopReps,loopMin,setLoopMin,pauseSeconds,setPauseSeconds,countInChoice,setCountInChoice,countInSubdiv,setCountInSubdiv,tone,setTone,sound,setSound,clickOn,setClickOn,clickEvery,setClickEvery,totalSec,onStart}=p;
 const [previewIndex,setPreviewIndex]=useState(0);const [busy,setBusy]=useState(false);const [previewing,setPreviewing]=useState(false);const [error,setError]=useState('');const alive=useRef(true);const handoff=useRef(false);const timer=useRef();
 useEffect(()=>{alive.current=true;return ()=>{alive.current=false;clearTimeout(timer.current);if(!handoff.current)stopGuitar();};},[]);
 useEffect(()=>{stopGuitar();setPreviewing(false);clearTimeout(timer.current);},[tone,position,bpm,practiceMode,focusCombo,focusCrossing,previewIndex,startStroke,bothStrokes,groups]);
 const ex=exercises[Math.min(previewIndex,exercises.length-1)];
 async function audio(preview){stopGuitar();clearTimeout(timer.current);if(preview&&previewing){setPreviewing(false);return;}setBusy(true);setError('');try{await primeMetronomeAudio();if(sound||preview)await prepareGuitar(getAudioContext(),tone);if(!alive.current)return;if(preview){const ctx=getAudioContext(),duration=30/bpm;ex.notes.forEach((n,i)=>n.midi.forEach(m=>pluck(ctx,m,ctx.currentTime+.08+i*duration,duration,.5)));setPreviewing(true);timer.current=setTimeout(()=>setPreviewing(false),(ex.notes.length*duration+.3)*1000);}else{handoff.current=true;await onStart();}}catch{setError('Sound could not load. Try Original synth or turn instrument sound off.');}finally{if(alive.current)setBusy(false);}}
 return <main className="cp-workspace picking-workspace"><fieldset disabled={busy} style={{border:0,padding:0,margin:0,minWidth:0}}>
 <section className="pk-hero"><div><div className="cp-eyebrow">TECHNIQUE / ALTERNATE PICKING</div><h1>ULTIMATE<br/>ALTERNATE PICKING</h1><p>Every fingering. Every crossing. Full attention.</p></div><img src={workout.cover} alt="Ultimate Alternate Picking Workout cover"/></section>
 <div className="pk-layout"><div><section className="pk-panel"><h2>01 FIND YOUR FOCUS</h2><Choices label="Practice" value={practiceMode} options={[["full","Full workout"],["focus","Focused practice"]]} onChange={v=>{setPracticeMode(v);setPreviewIndex(0);}}/>
 {practiceMode==='focus'?<><label className="cp-field">Fingering<select value={focusCombo} onChange={e=>{setFocusCombo(e.target.value);setGroups([2,3,4]);}}>{combos.map(c=><option key={c} value={c}>{c.split('').join('–')}</option>)}</select></label><Choices label="Crossing" value={focusCrossing} options={[["arpeggiated","Arpeggiated"],["adjacent","Adjacent strings"],["skipping","String skipping"]]} onChange={setFocusCrossing}/></>:<div className="cp-field"><span className="cp-label">Fingerings</span><div className="cp-choices">{[2,3,4].map(g=><button key={g} aria-pressed={groups.includes(g)} onClick={()=>{if(groups.includes(g)&&groups.length===1)return;setGroups(groups.includes(g)?groups.filter(x=>x!==g):[...groups,g].sort());setPreviewIndex(0);}}>{g}-finger</button>)}</div><p>Continuous from pattern to pattern, as written.</p></div>}
 <Choices label="Position · index finger fret" value={position} options={workout.positions.map(v=>[v,String(v)])} onChange={setPosition}/><Choices label="Passes" value={bothStrokes?'both':startStroke} options={[["D","Downstroke"],["U","Upstroke"],["both","Downstroke, then upstroke"]]} onChange={v=>{setBothStrokes(v==='both');if(v!=='both')setStroke(v);}}/>
 </section><section className="pk-panel"><h2>02 SEE THE PATTERN</h2>{practiceMode==='full'&&<label className="cp-field">Preview pattern<select value={Math.min(previewIndex,exercises.length-1)} onChange={e=>setPreviewIndex(Number(e.target.value))}>{exercises.map((e,i)=><option key={e.id} value={i}>{e.comboLabel} · {e.modeLabel} · {e.startStroke==='D'?'Downstroke':'Upstroke'}</option>)}</select></label>}
 <p>{ex.comboLabel} · {ex.modeLabel} · {ex.startStroke==='D'?'Downstroke':'Upstroke'} start</p><TabView notes={ex.notes} cursor={-1}/><p>⊓ Downstroke · ∨ Upstroke. Numbers show fingers; place finger 1 on fret {position}.</p><button className="pk-action" disabled={busy} onClick={()=>audio(true)}>{previewing?'Stop preview':'▷ Hear this pattern'}</button><PatternRating records={[{id:ex.baseId,stroke:ex.startStroke}]} position={position} bpm={bpm}/></section></div>
 <aside className="pk-panel"><h2>03 SET YOUR PACE</h2><NumberField deliberate label="Practice tempo" value={bpm} min={20} max={200} onChange={setBpm}/><p>BPM · eighth notes</p>
 {practiceMode==='focus'&&<><Choices label="Repeat each pattern" value={loopMode} options={[["off","Once"],["reps","Repetitions"],["timer","Timer"]]} onChange={setLoopMode}/>{loopMode==='reps'&&<NumberField deliberate label="Repetitions" value={loopReps} min={1} max={100} onChange={setLoopReps}/ >}{loopMode==='timer'&&<NumberField deliberate label="Minutes per pattern" value={loopMin} min={1} max={60} onChange={setLoopMin}/>}</>}
 <label className="cp-field">Instrument<select value={tone} onChange={e=>setTone(e.target.value)}>{[['piano','Grand piano'],['harpsichord','Harpsichord'],['electric','Clean electric'],['nylon','Nylon string'],['original','Original synth']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>
 <div className="cp-choices"><button role="switch" aria-checked={sound} onClick={()=>setSound(!sound)}>Instrument sound</button><button role="switch" aria-checked={clickOn} onClick={()=>setClickOn(!clickOn)}>Metronome</button></div><VolumeControls {...p}/>
 <details className="cp-timing"><summary>Timing & count-in</summary><Choices label="Count-in" value={countInChoice} options={[["bar","4 beats"],[2,"2 beats"]]} onChange={setCountInChoice}/><Choices label="Count-in subdivisions" value={countInSubdiv} options={[[false,"Off"],[true,"On"]]} onChange={setCountInSubdiv}/><Choices label="Metronome click" value={clickEvery} options={[["beat","The beat"],["all","Subdivisions"]]} onChange={setClickEvery}/>{(practiceMode==='focus'||bothStrokes)&&<Choices label="Rest before count-in" value={pauseSeconds} options={PAUSE_OPTIONS.map(v=>[v,v+'s'])} onChange={setPauseSeconds}/>}</details>
 <div className="pk-session"><span className="cp-label">YOUR SESSION</span><strong>~{fmtClock(totalSec)}</strong><p>{practiceMode==='focus'?'One pattern at a time':exercises.length+' patterns'} · Position {position}{bothStrokes?' · Downstroke, then upstroke':''}</p>{bothStrokes&&<p>A {pauseSeconds}s preparation break and a fresh count-in before the upstroke pass.</p>}<button className="pk-action" disabled={busy} onClick={()=>audio(false)}>{busy?'Preparing sound…':'Start practicing ▶'}</button>{error&&<p role="alert">{error}</p>}</div><p className="cp-muted">Relaxed hands. Accurate notes. Consistent tone.</p>
 </aside></div></fieldset></main>;
}
