import React,{useState,useRef} from 'react';
import {readLog,exportLog,importLog,dayKey,fmtDur,fmtClock} from './storage';
import {progressSessions,summarize} from './progressSummary';
import './workout-progress.css';
const duration=seconds=>seconds>0&&seconds<60?'<1m':fmtDur(seconds*1000);
export default function WorkoutProgress({onBack}){
 const [month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1));
 const [category,setCategory]=useState('All'),[selected,setSelected]=useState(null),[notice,setNotice]=useState(''),[version,refresh]=useState(0);
 const file=useRef(null),sessions=progressSessions(readLog().sessions);
 const categories=[...new Set(sessions.map(s=>s.category))].sort();
 const filtered=sessions.filter(s=>category==='All'||s.category===category);
 const monthKey=dayKey(month).slice(0,7),monthly=filtered.filter(s=>s.day.startsWith(monthKey)),stats=summarize(monthly);
 const days=new Map();monthly.forEach(s=>days.set(s.day,[...(days.get(s.day)||[]),s]));
 const workouts=[...new Set(monthly.map(s=>s.id))].map(id=>({meta:monthly.find(s=>s.id===id),sessions:monthly.filter(s=>s.id===id)}));
 const shown=selected?monthly.filter(s=>s.day===selected):monthly;
 const lead=(month.getDay()+6)%7,total=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();
 function move(delta){setMonth(new Date(month.getFullYear(),month.getMonth()+delta,1));setSelected(null);}
 return <div className="wp-page"><header><button onClick={onBack}>← Workouts</button><span>MY PROGRESS</span></header><main><div className="wp-eyebrow">YOUR PRACTICE, TAKING SHAPE</div><h1>My Progress</h1><p>A record of the time you put in and the workouts you come back to. Short sessions count too.</p>
 <nav className="wp-filters" aria-label="Technique filter">{['All',...categories].map(c=><button key={c} aria-pressed={category===c} onClick={()=>{setCategory(c);setSelected(null);}}>{c}</button>)}</nav>
 <div className="wp-month"><h2>{month.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h2><div><button aria-label="Previous month" onClick={()=>move(-1)}>←</button><button onClick={()=>{setMonth(new Date(new Date().getFullYear(),new Date().getMonth(),1));setSelected(null);}}>This month</button><button aria-label="Next month" onClick={()=>move(1)}>→</button></div></div>
 <div className="wp-stats">{[[stats.days,'Days practiced'],[duration(stats.seconds),'Practice time'],[workouts.length,'Workouts explored']].map(([v,l])=><div key={l}><strong>{v}</strong><span>{l}</span></div>)}</div>
 <div className="wp-layout"><section className="wp-panel"><h2>Your calendar</h2><p>Select a day to see what you practiced.</p><div className="wp-calendar">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(n=><span key={n}>{n}</span>)}{Array.from({length:lead},(_,i)=><span key={'blank'+i}/>)}{Array.from({length:total},(_,i)=>{const date=dayKey(new Date(month.getFullYear(),month.getMonth(),i+1)),list=days.get(date)||[],time=summarize(list).seconds;return <button key={date} aria-label={`${date}, ${list.length} sessions`} aria-pressed={selected===date} aria-current={date===dayKey(new Date())?'date':undefined} className={list.length?'wp-practiced':''} onClick={()=>setSelected(selected===date?null:date)}><b>{i+1}</b>{time>0&&<small>{duration(time)}</small>}</button>;})}</div></section>
 <section className="wp-panel"><div className="wp-month"><h2>{selected?new Date(selected+'T12:00:00').toLocaleDateString(undefined,{month:'long',day:'numeric'}):'Recent practice'}</h2>{selected&&<button onClick={()=>setSelected(null)}>Show month</button>}</div>{!shown.length?<p>{selected?'Nothing logged on this day.':'Your next session will appear here. Choose a workout and start practicing.'}</p>:<div className="wp-history">{shown.slice(0,selected?shown.length:8).map((s,i)=><article key={i}><span className="wp-eyebrow">{s.category} · {new Date(s.startedAt).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</span><h3>{s.title}</h3><p>{[s.key,s.position?`Position ${s.position}`:null,s.bpm?`${s.bpm} BPM`:null,s.mode==='hammers'?'All Hammers':null].filter(Boolean).join(' · ')}</p><strong>{fmtClock(s.seconds)} practiced</strong></article>)}</div>}</section></div>
 <h2>What you’ve been working on</h2><div className="wp-workouts">{workouts.map(({meta,sessions:list})=><article key={meta.id}>{meta.cover?<img src={meta.cover} alt=""/>:<div className="wp-cover">1 · 2 · 3 · 4</div>}<div><span className="wp-eyebrow">{meta.category}</span><h3>{meta.title}</h3><p>{list.length} {list.length===1?'session':'sessions'} · {summarize(list).days} {summarize(list).days===1?'day':'days'} practiced</p><strong>{duration(summarize(list).seconds)} this month</strong></div></article>)}</div>{!workouts.length&&<p>Your workout cards will appear here after you practice.</p>}
 <section className="wp-panel wp-backup"><h2>Keep your progress safe</h2><p>Progress stays in this browser. Export a JSON backup before switching devices or clearing browser data. Importing merges your sessions without replacing your current history.</p><button onClick={()=>{const n=exportLog();setNotice(`Exported ${n} sessions.`);}}>Export backup</button><button onClick={()=>file.current.click()}>Import backup</button><input ref={file} hidden type="file" accept=".json,application/json" onChange={async e=>{const input=e.target,f=input.files[0];if(!f)return;try{const result=importLog(JSON.parse(await f.text()));setNotice(result.ok?`Imported ${result.added} new sessions.`:result.error);refresh(version+1);}catch{setNotice('Could not read that JSON backup.');}input.value='';}}/><p role="status">{notice}</p></section>
 </main></div>;
}
