import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import ChromaticWorkout from './ChromaticWorkout';
import {configureAssets} from '../../../packages/workouts/engine/shared/assets';
import {EXERCISES} from './chromaticData';
import {read,fresh,write,validate,merge,completedDays,completedExercise,dateKey,emptyRow,counts} from './tracking';
import './site.css';
configureAssets('/vinnie');
function App(){
 const [view,setView]=useState('workout'),[version,setVersion]=useState(0),[notice,setNotice]=useState(''),[state,setState]=useState(()=>{try{return read();}catch{return fresh();}});
 useEffect(()=>{const update=()=>{try{setState(read());}catch{setNotice('Saved progress could not be read. Import a backup to recover it.');}},error=()=>setNotice('Progress could not be saved. Check browser storage and export a backup before leaving.');update();window.addEventListener('vinnie-progress',update);window.addEventListener('vinnie-save-error',error);return()=>{window.removeEventListener('vinnie-progress',update);window.removeEventListener('vinnie-save-error',error);};},[]);
 const days=completedDays(state),row=state.days[dateKey()]||emptyRow(),done=row.filter((_,i)=>completedExercise(row,i)).length;
 function download(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`vinnie-progress-${dateKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function upload(e){const file=e.target.files[0];if(!file)return;try{if(file.size>5000000)throw Error('Backup is too large.');const incoming=validate(JSON.parse(await file.text()));write(merge(read(),incoming));setVersion(v=>v+1);setNotice('Progress imported. Existing progress has been kept.');}catch(error){setNotice(error.message);}e.target.value='';}
 return <><nav className="vinnie-nav"><a href="/">JON BJORK / MUSIC</a><button onClick={()=>setView('workout')} aria-pressed={view==='workout'}>Workout</button><button onClick={()=>setView('progress')} aria-pressed={view==='progress'}>My progress · {Math.min(30,days.length)} / 30</button></nav>
 {view==='workout'?<ChromaticWorkout key={version} onBack={()=>{window.location.href='/';}}/>:<main className="vinnie-tracker"><h1>Your 30-day progress</h1><p>Today: {done} of {EXERCISES.length} exercises complete. Complete all twelve to mark a day. Miss a day? Your progress stays here.</p><div className="vinnie-days">{Array.from({length:30},(_,i)=><div key={i} className={i<days.length?'complete':''}><strong>Day {i+1} {i<days.length?'✓':''}</strong><small>{days[i]||'Not completed yet'}</small></div>)}</div><div className="vinnie-milestones">{[[7,'First week'],[14,'Two weeks'],[21,'Three weeks'],[30,'30 days of practice']].map(([n,title])=><p key={n}>{days.length>=n?'✓ ':''}{title} · {Math.min(n,days.length)} / {n}</p>)}</div><h2>Today’s exercises</h2>{EXERCISES.map((e,i)=><p key={e.id}>{completedExercise(row,i)?'✓ ':''}{e.title} · {row[i].length} / {counts[i]} positions</p>)}<details><summary>Practice history</summary>{Object.entries(state.days).sort(([a],[b])=>b.localeCompare(a)).map(([day,r])=><p key={day}>{day} · {r.filter((_,i)=>completedExercise(r,i)).length} of 12 exercises complete</p>)}</details></main>}
 <footer className="vinnie-tracker"><h2>Keep your progress</h2><p>Saved in this browser after each completed position. Export a backup to move devices. Import merges progress without removing completed positions.</p><button onClick={download}>Export JSON</button><label className="vinnie-import">Import JSON<input type="file" accept=".json,application/json" onChange={upload}/></label><p role="status">{notice}</p><p>More guided practice inside <a href="/practiceroom/?ref=vinnie">The Practice Room ↗</a></p><p>All current and future courses, plus all updates to the Practice Lab app. One-time payment. No subscription.</p><a href="/vinnie/audio/CREDITS.txt">Sound credits</a> · <a href="/legal/">Privacy & terms</a></footer></>;
}
createRoot(document.getElementById('root')).render(<App/>);
